#!/usr/bin/env tsx
/**
 * Development environment setup script
 * Creates a data directory with dummy data for local development
 */

import { execSync } from "child_process";
import fs from "fs/promises";
import path from "path";

const DATA_DIR = path.join(process.cwd(), "data");

interface SetupOptions {
  organizers?: number;
  days?: number;
  seed?: number;
  force?: boolean;
}

/**
 * Parse command line arguments
 */
function parseArgs(): SetupOptions {
  const args = process.argv.slice(2);
  const options: SetupOptions = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    switch (arg) {
      case "--organizers":
        options.organizers = parseInt(args[++i], 10);
        break;
      case "--days":
        options.days = parseInt(args[++i], 10);
        break;
      case "--seed":
        options.seed = parseInt(args[++i], 10);
        break;
      case "--force":
      case "-f":
        options.force = true;
        break;
      case "--help":
      case "-h":
        console.log(`
Development Setup Script

Usage: pnpm setup:dev [options]

Options:
  --organizers <n>  Number of organizers to generate (default: 30)
  --days <n>          Number of days back for races (default: 90)
  --seed <n>          Seed for reproducible data generation
  --force, -f         Force overwrite existing data directory
  --help, -h          Show this help message

Examples:
  pnpm setup:dev
  pnpm setup:dev --organizers 50 --days 60
  pnpm setup:dev --seed 12345 --force
        `);
        process.exit(0);
    }
  }

  return options;
}

/**
 * Check if data directory exists
 */
async function checkDataDir(): Promise<boolean> {
  try {
    await fs.access(DATA_DIR);
    return true;
  } catch {
    return false;
  }
}

/**
 * Create directory structure
 */
async function createDirStructure(): Promise<void> {
  console.log("📁 Creating directory structure...");

  await fs.mkdir(DATA_DIR, { recursive: true });
  await fs.mkdir(path.join(DATA_DIR, "organizers"), { recursive: true });
  await fs.mkdir(path.join(DATA_DIR, "races", "organizers"), {
    recursive: true,
  });

  console.log("   ✓ Created data/");
  console.log("   ✓ Created data/organizers/");
  console.log("   ✓ Created data/races/organizers/");
}

/**
 * Generate config.yaml
 */
async function generateConfig(options: SetupOptions): Promise<void> {
  console.log("⚙️  Generating config.yaml...");

  const config = `# Starter Configuration (Development)
# Generated by setup-dev script

org:
  name: "Example Organization"
  description: "A sample organization for local development"
  url: "https://example.com"
  logo_url: "https://api.dicebear.com/7.x/shapes/svg?seed=example"
  start_date: "2022-01-01"

meta:
  title: "Example Site"
  description: "Local development site with dummy data"
  site_url: "http://localhost:3000"
  image_url: "https://api.dicebear.com/7.x/shapes/svg?seed=example"
  favicon_url: "https://api.dicebear.com/7.x/shapes/svg?seed=example"

leaderboard:
  # Dummy plugin configuration
  plugins:
    dummy:
      source: "file://${process.cwd()}/packages/plugin-dummy/dist/index.js"
      config:
        organizers:
          count: ${options.organizers || 30}
          minRacesPerOrganizer: 5
          maxRacesPerOrganizer: 100
        races:
          daysBack: ${options.days || 90}${
            options.seed !== undefined
              ? `\n          seed: ${options.seed}`
              : ""
          }
        sources:
          - "source-a"
          - "source-b"
          - "source-c"

  # Badge definitions and evaluation rules
  badges:
    definitions:
      - slug: race_milestone
        name: "Race Milestone"
        description: "Awarded for reaching race count milestones"
        variants:
          bronze:
            description: "10+ races"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=bronze-race"
          silver:
            description: "50+ races"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=silver-race"
          gold:
            description: "100+ races"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=gold-race"
          platinum:
            description: "500+ races"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=platinum-race"
      - slug: points_milestone
        name: "Points Milestone"
        description: "Awarded for reaching points milestones"
        variants:
          bronze:
            description: "100+ points"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=bronze-points"
          silver:
            description: "500+ points"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=silver-points"
          gold:
            description: "1,000+ points"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=gold-points"
          platinum:
            description: "5,000+ points"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=platinum-points"
      - slug: consistency_champion
        name: "Consistency Champion"
        description: "Awarded for maintaining race streaks"
        variants:
          bronze:
            description: "7 day streak"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=bronze-streak"
          silver:
            description: "14 day streak"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=silver-streak"
          gold:
            description: "30 day streak"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=gold-streak"
          platinum:
            description: "90 day streak"
            svg_url: "https://api.dicebear.com/7.x/shapes/svg?seed=platinum-streak"
    rules:
      - type: threshold
        badge_slug: race_milestone
        enabled: true
        aggregate_slug: race_count
        thresholds:
          - variant: bronze
            value: 10
          - variant: silver
            value: 50
          - variant: gold
            value: 100
          - variant: platinum
            value: 500
      - type: threshold
        badge_slug: points_milestone
        enabled: true
        aggregate_slug: total_race_points
        thresholds:
          - variant: bronze
            value: 100
          - variant: silver
            value: 500
          - variant: gold
            value: 1000
          - variant: platinum
            value: 5000
      - type: streak
        badge_slug: consistency_champion
        enabled: true
        streak_type: daily
        thresholds:
          - variant: bronze
            days: 7
          - variant: silver
            days: 14
          - variant: gold
            days: 30
          - variant: platinum
            days: 90
`;

  await fs.writeFile(path.join(DATA_DIR, "config.yaml"), config, "utf-8");
  console.log("   ✓ Generated config.yaml");
}

/**
 * Build the dummy plugin
 */
async function buildDummyPlugin(): Promise<void> {
  console.log("🔨 Building dummy plugin...");

  try {
    execSync("pnpm --filter @starter/plugin-dummy build", {
      stdio: "inherit",
    });
    console.log("   ✓ Plugin built successfully\n");
  } catch (error) {
    console.error("\n❌ Failed to build plugin");
    throw error;
  }
}

/**
 * Create theme.css placeholder
 */
async function createThemeFile(): Promise<void> {
  console.log("🎨 Creating theme.css placeholder...");

  const themePath = path.join(DATA_DIR, "theme.css");
  const themeContent = `/* Custom theme overrides for your leaderboard */
/* This file is optional - you can customize colors, fonts, and styles here */

/* Example: Customize colors */
/*
:root {
  --primary: oklch(0.5 0.2 250);
  --accent: oklch(0.7 0.15 180);
}
*/

/* Example: Customize fonts */
/*
body {
  font-family: 'Your Custom Font', sans-serif;
}
*/

/* Example: Customize the people grid */
/*
:root {
  --people-grid-cols-mobile: 6;
  --people-grid-cols-md: 10;
  --people-grid-cols-lg: 14;
}
*/
`;

  await fs.writeFile(themePath, themeContent, "utf-8");
  console.log("   ✓ Created theme.css\n");
}

/**
 * Run plugin runner to generate data
 */
async function runPluginRunner(): Promise<void> {
  console.log("🔌 Running plugin runner to generate data...");
  console.log("──────────────────────────────────────\n");

  try {
    execSync("pnpm build:data", {
      stdio: "inherit",
      env: {
        ...process.env,
        LEADERBOARD_DATA_DIR: DATA_DIR,
      },
    });
  } catch (error) {
    console.error("\n❌ Failed to run plugin runner");
    throw error;
  }
}

/**
 * Display success message
 */
function displaySuccess(options: SetupOptions): void {
  console.log("\n╔════════════════════════════════════════╗");
  console.log("║   ✨ Development Setup Complete! ✨   ║");
  console.log("╚════════════════════════════════════════╝\n");

  console.log("📊 Configuration:");
  console.log(`   Organizers: ${options.organizers || 30}`);
  console.log(`   Time Period: Last ${options.days || 90} days`);
  if (options.seed !== undefined) {
    console.log(`   Seed: ${options.seed} (reproducible)`);
  }

  console.log("\n📁 Data Directory:");
  console.log(`   ${DATA_DIR}`);

  console.log("\n🚀 Next Steps:");
  console.log("   1. Start the development server:");
  console.log("      pnpm dev");
  console.log("\n   2. Open your browser:");
  console.log("      http://localhost:3000");
  console.log("\n   3. Make changes and see them live!");

  console.log("\n📚 Reference:");
  console.log("   • Dummy Plugin: packages/plugin-dummy/README.md");
  console.log("   • Plugin API: packages/api/src/types.ts");

  console.log("\n🔧 Useful Commands:");
  console.log("   pnpm clean:dev    Remove data directory");
  console.log("   pnpm reset:dev    Clean and regenerate data");
  console.log("   pnpm setup:dev    Run this setup again");

  console.log("");
}

/**
 * Main setup function
 */
async function main() {
  console.log("\n🎯 Starter Development Setup\n");

  const options = parseArgs();

  // Check if data directory exists
  const exists = await checkDataDir();

  if (exists && !options.force) {
    console.log("⚠️  Data directory already exists!");
    console.log("   Use --force to overwrite or run 'pnpm clean:dev' first.\n");
    process.exit(1);
  }

  if (exists && options.force) {
    console.log("🗑️  Removing existing data directory...");
    await fs.rm(DATA_DIR, { recursive: true, force: true });
    console.log("   ✓ Removed\n");
  }

  try {
    // Create directory structure
    await createDirStructure();

    // Generate config
    await generateConfig(options);

    // Create empty theme.css as placeholder
    await createThemeFile();

    // Build plugin
    await buildDummyPlugin();

    // Run plugin runner
    await runPluginRunner();

    // Display success message
    displaySuccess(options);
  } catch (error) {
    console.error("\n❌ Setup failed:", error);
    process.exit(1);
  }
}

// Run the script
main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
